name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify API Deploy
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK_API }}" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"